#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7

# _extract_id URL-or-ID prints the Drive id out of a pasted URL, or returns the
# input unchanged when it is already a bare id.
_extract_id() {
  local raw="$1"
  if   [[ "$raw" =~ /d/([a-zA-Z0-9_-]+) ]];       then printf '%s' "${BASH_REMATCH[1]}"
  elif [[ "$raw" =~ /folders/([a-zA-Z0-9_-]+) ]]; then printf '%s' "${BASH_REMATCH[1]}"
  else printf '%s' "$raw"; fi
}

# _gitignore_has PATTERN appends PATTERN to .gitignore unless already present.
_gitignore_has() {
  local pattern="$1"
  touch .gitignore
  if ! grep -qxF "$pattern" .gitignore 2>/dev/null; then
    printf '%s\n' "$pattern" >> .gitignore
    printf '  %s+ added%s %s to .gitignore\n' "$GREEN" "$RESET" "$pattern"
  fi
}

FOLDER_ID="1Ew4F4HTwJ6TJ5uG3YLKinjzpzEVTuunV"
WORKBOOK_ID="1TNyT7hZ7TUXyw0szJGjET6H-T_NaqqbXPoeuJytLTss"
KEY_PATH="secrets/service-account.json"

if [[ ! -f CLAUDE.md || ! -d .git ]]; then
  printf '\n  %sRun this from the mousai repo root, not from %s%s\n\n' "$RED" "$PWD" "$RESET"
  exit 1
fi

banner "Google access for mousai"

# -- 1 ---------------------------------------------------------------------
stage "Google Cloud project"
say "The app talks to Sheets through a service account, which needs a project"
say "to live in. A personal Gmail is fine; you do not need an organisation."
open_url "https://console.cloud.google.com/projectcreate"
step "Name it something like mousai and click Create."
step "Wait for the notification, then open the project."
step "The Project ID sits under the name; it may have digits appended."
ask GCP_PROJECT_ID "Paste the Project ID:"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"

# -- 2 ---------------------------------------------------------------------
stage "Enable the three APIs"
say "Sheets to read and write cells, Drive to list the Workbooks in the folder,"
say "Vision to read the amount off a photographed receipt."
open_url "https://console.cloud.google.com/apis/library/sheets.googleapis.com?project=${GCP_PROJECT_ID}"
step "Click Enable on the Google Sheets API. Wait for it to finish."
pause "Enabled Sheets? Press Enter for the Drive API."
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com?project=${GCP_PROJECT_ID}"
step "Click Enable on the Google Drive API."
pause "Enabled Drive? Press Enter for the Vision API."
open_url "https://console.cloud.google.com/apis/library/vision.googleapis.com?project=${GCP_PROJECT_ID}"
step "Click Enable on the Cloud Vision API."
warn "Vision needs a billing account on the project, even inside the free tier"
warn "(1,000 images a month). Sheets and Drive do not."
note "Skipping this one is survivable: receipt photos then fall back to typing,"
note "with a note on the preview. Everything else still works."
pause "All three enabled?"

# -- 3 ---------------------------------------------------------------------
stage "Create the service account"
say "This becomes the app own identity. Its name is what you will see in"
say "Show edit history on every cell the app writes, so pick something you"
say "will still recognise in a year."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create?project=${GCP_PROJECT_ID}"
step "Service account name: mousai-writer"
step "Click Create and Continue."
warn "Do NOT grant it any project role. Skip that step entirely."
note "Access to the sheets comes from sharing the Drive folder in stage 5, not"
note "from project IAM. Granting roles here would give it more than it needs."
step "Click Done. You land back on the service accounts list."
step "Copy the account email; it ends in .iam.gserviceaccount.com"
ask GOOGLE_SERVICE_ACCOUNT_EMAIL "Paste the service account email:"
write_env GOOGLE_SERVICE_ACCOUNT_EMAIL "$GOOGLE_SERVICE_ACCOUNT_EMAIL"

# -- 4 ---------------------------------------------------------------------
stage "Download the key"
say "A JSON key file is the account password. It never goes in git."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts?project=${GCP_PROJECT_ID}"
step "Click the mousai-writer account, then the Keys tab."
step "Add key, then Create new key, then JSON, then Create."
step "Your browser downloads a .json file. Note where it landed."
warn "If key creation is blocked, an org policy is disabling it. On a personal"
warn "Gmail that should not happen; on a work account, ask your admin."
ask KEY_DOWNLOAD_PATH "Full path to the downloaded .json:"
KEY_DOWNLOAD_PATH="${KEY_DOWNLOAD_PATH/#\~/$HOME}"
KEY_DOWNLOAD_PATH="${KEY_DOWNLOAD_PATH%\"}"
KEY_DOWNLOAD_PATH="${KEY_DOWNLOAD_PATH#\"}"
if [[ -f "$KEY_DOWNLOAD_PATH" ]]; then
  mkdir -p "$(dirname "$KEY_PATH")"
  mv "$KEY_DOWNLOAD_PATH" "$KEY_PATH"
  chmod 600 "$KEY_PATH" 2>/dev/null || true
  printf '  %s+ moved%s key to %s\n' "$GREEN" "$RESET" "$KEY_PATH"
else
  warn "No file at that path. Move it to $KEY_PATH yourself before running the app."
  SKIPPED+=("move the JSON key to $KEY_PATH")
fi
_gitignore_has "secrets/"
_gitignore_has ".env"
write_env GOOGLE_APPLICATION_CREDENTIALS "$KEY_PATH"

# -- 5 ---------------------------------------------------------------------
stage "Share the Drive folder"
say "Sharing the FOLDER, not a file, is what makes next month Workbook work"
say "without anyone touching this setup again."
write_env MOUSAI_DRIVE_FOLDER_ID "$FOLDER_ID"
open_url "https://drive.google.com/drive/folders/${FOLDER_ID}"
step "Click the folder name at the top, then Share, then Share."
say "Paste this address into the people box:"
printf '\n      %s%s%s\n\n' "$BOLD" "$GOOGLE_SERVICE_ACCOUNT_EMAIL" "$RESET"
step "Set its role to Editor."
warn "Untick Notify people. Mail to a service account just bounces."
step "Click Share."
pause "Shared as Editor?"

# -- 6 ---------------------------------------------------------------------
stage "Put the Workbook in the folder"
say "The folder is empty right now, so the app has nothing to find."
open_url "https://docs.google.com/spreadsheets/d/${WORKBOOK_ID}/edit"
step "File, then Move, then choose M_example_sheets, then Move."
pause "Moved?"
say "Now a throwaway copy for the tests to write into, so that no test ever"
say "touches the real Workbook."
open_url "https://drive.google.com/drive/folders/${FOLDER_ID}"
step "Right-click the Workbook, then Make a copy."
step "Rename the copy to: TEST scratch - do not use"
step "Move the copy OUT of M_example_sheets. My Drive is fine."
warn "Keep that folder for real Workbooks only. The picker offers the most"
warn "recently modified one, and a test copy would win almost every time."
note "The app also excludes this id from the picker once it is in .env, but"
note "keeping the folder clean is the part that does not depend on config."
step "Open the copy."
ask TEST_SHEET_RAW "Paste the copy URL (or just its id):"
MOUSAI_TEST_SPREADSHEET_ID="$(_extract_id "$TEST_SHEET_RAW")"
write_env MOUSAI_TEST_SPREADSHEET_ID "$MOUSAI_TEST_SPREADSHEET_ID"

# -- 7 ---------------------------------------------------------------------
stage "Checks"
say "Local checks only. Nothing here calls Google; the first real proof that"
say "the credentials work is the reconciliation run against the live Workbook."
if [[ -f "$KEY_PATH" ]]; then
  printf '  %s+%s key file present at %s\n' "$GREEN" "$RESET" "$KEY_PATH"
  if grep -q 'client_email' "$KEY_PATH" 2>/dev/null; then
    printf '  %s+%s looks like a service account key\n' "$GREEN" "$RESET"
    if grep -qF "$GOOGLE_SERVICE_ACCOUNT_EMAIL" "$KEY_PATH" 2>/dev/null; then
      printf '  %s+%s key belongs to %s\n' "$GREEN" "$RESET" "$GOOGLE_SERVICE_ACCOUNT_EMAIL"
    else
      warn "the key client_email does not match the address pasted in stage 3;"
      warn "you may have downloaded a key for a different service account"
    fi
  else
    warn "that file has no client_email; is it really the service account key?"
  fi
  if git check-ignore -q "$KEY_PATH" 2>/dev/null; then
    printf '  %s+%s git is ignoring the key\n' "$GREEN" "$RESET"
  else
    warn "git is NOT ignoring $KEY_PATH. Do not commit until that is fixed."
    SKIPPED+=("stop git tracking $KEY_PATH")
  fi
else
  warn "no key at $KEY_PATH yet"
fi
pause "Done reading?"

finish
note "Next: the reconciliation run, comparing all 21 sheets of the live Workbook"
note "against the baseline extracted from the original .xlsx."
printf '\n'
